repos:
  - repo: https://github.com/psf/black.git
    rev: 23.7.0
    hooks:
    -   id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    -   id: mypy
  - repo: https://github.com/pylint-dev/pylint.git
    rev: v2.17.5
    hooks:
    -   id: pylint
    