dataset:
  download: True
  dataset_root_path: "/Volumes/pherkel 2/SWR2-ASR" # files will be downloaded into this dir
  language_name: "mls_german_opus"
  limited_supervision: True # set to True if you want to use limited supervision
  dataset_percentage: 0.01 # percentage of dataset to use (1.0 = 100%)
  shuffle: True

model: 
  n_cnn_layers: 3
  n_rnn_layers: 5
  rnn_dim: 512
  n_feats: 128 # number of mel features
  stride: 2
  dropout: 0.6 # recommended to be around 0.4 for smaller datasets, 0.1 for really large datasets

tokenizer:
  tokenizer_path: "data/tokenizers/char_tokenizer_german.json"

decoder:
  type: "lm" # greedy, or lm (beam search)
  
  lm: # config for lm decoder
    language_model_path: "data" # path where model and supplementary files are stored
    language: "german"
    n_gram: 5 # n-gram size of the language model, 3 or 5
    beam_size: 500 
    beam_threshold: 150
    n_best: 1
    lm_weight: 2
    word_score: -2

training:
  learning_rate: 0.0005
  batch_size: 8 # recommended to maximum number that fits on the GPU (batch size of 32 fits on a 12GB GPU)
  epochs: 100
  eval_every_n: 1 # evaluate every n epochs
  num_workers: 8 # number of workers for dataloader

checkpoints: # use "~" to disable saving/loading
  model_load_path: "data/epoch67" # path to load model from
  model_save_path: ~ # path to save model to

inference:
  model_load_path: "data/epoch67" # path to load model from
