# a pod for testing the torch implementation of nms on a gpu
apiVersion: v1
kind: Pod
metadata:
  name: swr-asr
  labels:
    app: swr-asr
spec:
  initContainers:
    - name: swr-asr-init
      image: pherkel/swr2-asr
      imagePullPolicy: Always
      command: ["/bin/sh", "-c", "cp -R /app/* /tmp/"]
      volumeMounts:
        - name: swr-asr-vol
          mountPath: /tmp

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]


  containers:
    - name: swr-asr
      image: pherkel/swr2-asr
      imagePullPolicy: Always
      # command: ["/bin/bash", "-c", "while sleep 1000; do :; done"]

      volumeMounts:
        - name: swr-asr-vol
          mountPath: /app

        # workaround for increasing worker shared memory size
        - name: shm-vol
          mountPath: /dev/shm

      resources:
        requests:
          nvidia.com/gpu: "1"
          memory: "8Gi"
          cpu: "4"
        limits:
          nvidia.com/gpu: "1"
          memory: "8Gi"
          cpu: "4"

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]

  volumes:
    - name: swr-asr-vol
      persistentVolumeClaim:
        claimName: swr-asr-vol
    - name: shm-vol
      emptyDir:
        medium: Memory

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  nodeSelector:
    optocycle.com/infrastructure-provider: ocs
