apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swr-asr-vol
  labels:
    app: swr-asr
spec:
  storageClassName: ocs-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # enough to download and unzip the dataset
      storage: 82Gi
