[tool.poetry]
name = "swr2_asr"
version = "0.1.0"
description = "Automatic speech recognition with pytorch for SWR2"
authors = ["Philipp Merkel <philippmerkel@outlook.com>", "Marvin Borner <git@marvinborner.de>", "Valentin Schmidt <>", "Silja Kasper <>"]
license = "MIT"
readme = "readme.md"
packages = [{include = "swr2_asr"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.25.2"
click = "^8.1.6"

[tool.poetry.group.cpu]
optional = true

[tool.poetry.group.cpu.dependencies]
torch = "=2.0.1"
torchaudio = "=2.0.2"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pylint = "^2.17.5"
mypy = "^1.5.1"
pre-commit = "^3.3.3"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu111/"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.mypy.overrides]]
module = "torchaudio.*"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
