[tool.poetry]
name = "swr2_asr"
version = "0.1.0"
description = "Automatic speech recognition with pytorch for SWR2"
authors = ["Philipp Merkel <philippmerkel@outlook.com>", "Marvin Borner <git@marvinborner.de>", "Valentin Schmidt <>", "Silja Kasper <>"]
license = "MIT"
readme = "readme.md"
packages = [{include = "swr2_asr"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.25.2"
click = "^8.1.6"
audioloader = {git = "https://github.com/KinWaiCheuk/AudioLoader.git"}
tqdm = "^4.66.1"
torch = {version = "^2.0.1+cpu", source = "pytorch-cpu"}
torchaudio = {version = "^2.0.2+cpu", source = "pytorch-cpu"}

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pylint = "^2.17.5"
mypy = "^1.5.1"
pre-commit = "^3.3.3"

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[[tool.mypy.overrides]]
module = "torchaudio.*"
ignore_missing_imports = true

[tool.poetry.scripts]
train = "swr2_asr.train:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
